### ISSUE TITLE
xcltk baf - AssertionError

### ISSUE THREAD

**Issue by stublakemore** [hxj5/xcltk#10]
Dear Xianjie,

Thanks for the amazing package! However, I'm running into an issue when running xcltlk baf, where an AssertionError occurs:

[xcltk baf AssertionError.pdf](https://github.com/user-attachments/files/17712008/xcltk.baf.AssertionError.pdf)

It would be great if you can point me in the right direction what's going wrong... I'm running xcltk in a conda environment on a MacBook Pro, and running it using files on a server (not sure whether this might somehow be causing the issue?).

Many thanks,

Stuart

**Comment by hxj5** [comment]
Hi Stuart, thanks for the detailed feedback. According to the log file, it seems some phased VCF files are missing, possibly due to failing to access the net-file on server or errors in reference phasing with Eagle2. 

Can you check whether the phased VCF files (with suffix `.phased.vcf.gz`) for all autosome chromosomes, e.g., chr1 to 22 if human genome, are present in the `phasing` folder? If some phased files are indeed missing, can you share the corresponding log file in `scripts/phasing/` folder? Thanks!

**Comment by stublakemore** [comment]
Dear Xianjie,

Thank you for your quick response! Unfortunately I don't have any .phased.vcf.gz files, but I do have .vcf.gz and vcf.gz.csi files for chr1-22, which are all in the phasing folder. So I guess based on what you were expecting they're all missing? Here the zipped scripts/phasing/ folder as requested. 

Cheers,

Stuart

[phasing.zip](https://github.com/user-attachments/files/17727569/phasing.zip)

**Comment by stublakemore** [comment]
Dear Xianjie,

After reading into the eagle release information, I found out it was only ever optimised for linux. Although unix on Mac OS is a very similar operating system to linux, I couldn't figure out how to fix the AssertionError issue in unix. However, installing xcltk exactly as you described on our high performance computer (which is a linux system) solved the issue. For future readers of this issue that are also Mac OS users without access to a HPC, I would recommend installing a virtual box (for example here: https://macpaw.com/how-to/install-linux-on-mac).

Many thanks for your support,

Stuart
